Outputs:
  SubnetId:
    Description: InstanceId of the newly created EC2 instance
    Export:
      Name: SubnetId-jdix
    Value: !Ref 'Subnet'
  VpcId:
    Description: InstanceId of the newly created EC2 instance
    Export:
      Name: VpcId-jdix
    Value: !Ref 'Vpc'
Parameters:
  eastPeerCidrParam:
    Type: String
  subnetCidrParam:
    Description: string of subnet cidr block to use
    Type: String
  vpcCidrParam:
    Description: string of vpc cidr block to use
    Type: String
Resources:
  MyAllOutNetAclEntry:
    Properties:
      CidrBlock: '0.0.0.0/0'
      Egress: true
      NetworkAclId: !Ref 'MyFirstNetAcl'
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Type: AWS::EC2::NetworkAclEntry
  MyBucketForServiceConnection:
    Properties:
      BucketName: bucket-for-service-connection-lab-4-2-3-jdix
    Type: AWS::S3::Bucket
  MyFirstNetAcl:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::NetworkAcl
  MyPriv2PubNetAclEntry:
    Properties:
      CidrBlock: !Ref 'eastPeerCidrParam'
      NetworkAclId: !Ref 'MyFirstNetAcl'
      Protocol: -1
      RuleAction: allow
      RuleNumber: 101
    Type: AWS::EC2::NetworkAclEntry
  MyS3ClientPortsNetAclEntry1:
    Properties:
      CidrBlock: 3.5.76.0/22
      NetworkAclId: !Ref 'MyFirstNetAcl'
      PortRange:
        From: 1024
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 102
    Type: AWS::EC2::NetworkAclEntry
  MyS3ClientPortsNetAclEntry2:
    Properties:
      CidrBlock: 3.5.80.0/21
      NetworkAclId: !Ref 'MyFirstNetAcl'
      PortRange:
        From: 1024
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 103
    Type: AWS::EC2::NetworkAclEntry
  MyS3ClientPortsNetAclEntry3:
    Properties:
      CidrBlock: 52.218.128.0/17
      NetworkAclId: !Ref 'MyFirstNetAcl'
      PortRange:
        From: 1024
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 104
    Type: AWS::EC2::NetworkAclEntry
  MyS3ClientPortsNetAclEntry4:
    Properties:
      CidrBlock: 52.92.128.0/17
      NetworkAclId: !Ref 'MyFirstNetAcl'
      PortRange:
        From: 1024
        To: 65535
      Protocol: 6
      RuleAction: allow
      RuleNumber: 105
    Type: AWS::EC2::NetworkAclEntry
  MyVpcS3Endpoint:
    Properties:
      PolicyDocument:
        Statement:
          - Action: '*'
            Effect: Allow
            Principal: '*'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'MyBucketForServiceConnection'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'MyBucketForServiceConnection'
                  - /*
      RouteTableIds:
        - !Ref 'RouteTable'
      ServiceName: com.amazonaws.us-west-2.s3
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::VPCEndpoint
  RouteTable:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::RouteTable
  RouteTblSubnetAsoc:
    Properties:
      RouteTableId: !Ref 'RouteTable'
      SubnetId: !Ref 'Subnet'
    Type: AWS::EC2::SubnetRouteTableAssociation
  Subnet:
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Ref 'subnetCidrParam'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::Subnet
  Vpc:
    Properties:
      CidrBlock: !Ref 'vpcCidrParam'
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
    Type: AWS::EC2::VPC
  bucketPolicyForVpcEndpoint:
    Properties:
      Bucket: !Ref 'MyBucketForServiceConnection'
      PolicyDocument:
        Statement:
          - Action: '*'
            Condition:
              StringEquals:
                aws:SourceVpc: !Ref 'Vpc'
            Effect: Allow
            Principal: '*'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'MyBucketForServiceConnection'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'MyBucketForServiceConnection'
                  - /*
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
  peerRoute:
    Properties:
      DestinationCidrBlock: !Ref 'eastPeerCidrParam'
      RouteTableId: !Ref 'RouteTable'
      VpcPeeringConnectionId: pcx-0d27f0252e6c8ac93
    Type: AWS::EC2::Route
  subNaclAsoc:
    Properties:
      NetworkAclId: !Ref 'MyFirstNetAcl'
      SubnetId: !Ref 'Subnet'
    Type: AWS::EC2::SubnetNetworkAclAssociation
