Outputs:
  SubnetId:
    Description: InstanceId of the newly created EC2 instance
    Export:
      Name: SubnetId-jdix
    Value: !Ref 'Subnet'
  VpcId:
    Description: InstanceId of the newly created EC2 instance
    Export:
      Name: VpcId-jdix
    Value: !Ref 'Vpc'
Parameters:
  eastPeerCidrParam:
    Type: String
  subnetCidrParam:
    Description: string of subnet cidr block to use
    Type: String
  vpcCidrParam:
    Description: string of vpc cidr block to use
    Type: String
Resources:
  MyAllOutNetAclEntry:
    Properties:
      CidrBlock: '0.0.0.0/0'
      Egress: true
      NetworkAclId: !Ref 'MyFirstNetAcl'
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Type: AWS::EC2::NetworkAclEntry
  MyFirstNetAcl:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::NetworkAcl
  MyPriv2PubNetAclEntry:
    Properties:
      CidrBlock: !Ref 'eastPeerCidrParam'
      NetworkAclId: !Ref 'MyFirstNetAcl'
      Protocol: -1
      RuleAction: allow
      RuleNumber: 101
    Type: AWS::EC2::NetworkAclEntry
  RouteTable:
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::RouteTable
  RouteTblSubnetAsoc:
    Properties:
      RouteTableId: !Ref 'RouteTable'
      SubnetId: !Ref 'Subnet'
    Type: AWS::EC2::SubnetRouteTableAssociation
  Subnet:
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Ref 'subnetCidrParam'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::Subnet
  Vpc:
    Properties:
      CidrBlock: !Ref 'vpcCidrParam'
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-2
        - Key: user
          Value: josh.dix.labs
    Type: AWS::EC2::VPC
  peerRoute:
    Properties:
      DestinationCidrBlock: !Ref 'eastPeerCidrParam'
      RouteTableId: !Ref 'RouteTable'
      VpcPeeringConnectionId: pcx-0d27f0252e6c8ac93
    Type: AWS::EC2::Route
  subNaclAsoc:
    Properties:
      NetworkAclId: !Ref 'MyFirstNetAcl'
      SubnetId: !Ref 'Subnet'
    Type: AWS::EC2::SubnetNetworkAclAssociation
