Outputs:
  SubnetId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'Subnet'
  vpcId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'Vpc'
Parameters:
  subnetCidrParam:
    Description: string of subnet cidr block to use
    Type: String
  vpcCidrParam:
    Description: string of vpc cidr block to use
    Type: String
Resources:
  Subnet:
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Ref 'subnetCidrParam'
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-1
        - Key: user
          Value: josh.dix.labs
      VpcId: !Ref 'Vpc'
    Type: AWS::EC2::Subnet
  Vpc:
    Properties:
      CidrBlock: !Ref 'vpcCidrParam'
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
        - Key: stelligent_u_lab
          Value: lab-1
        - Key: stelligent_u_lesson
          Value: lesson-4-1
        - Key: user
          Value: josh.dix.labs
    Type: AWS::EC2::VPC
