Resources:
  LogicIdOfBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [ BucketName , Fn::Join: [ "-", [ Ref: "AWS::AccountId", 1-1-5-jdix ] ], Fn::Join: [ "-", [ Ref: "AWS::Region", 1-1-5-jdix ] ] ]

Conditions:
  BucketName: !Equals [ Ref: AWS::Region, us-east-2 ]
