Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stelligent-u-josh-dix-labs
      AccessControl: "AuthenticatedRead"
      VersioningConfiguration:
        Status: Enabled
  s3ReaderPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: s3_reader_user_lab_2_3_1_jdix
      Path: '/'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:ListBucket
          Resource: 'arn:aws:s3:::stelligent-u-josh-dix-labs'
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          - s3:DeleteObject
          Resource: 'arn:aws:s3:::stelligent-u-josh-dix-labs/*'
      Users:
        - josh.dix.labs
  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: stelligent-u-josh-dix-labs
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            NotResource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - stelligent-u-josh-dix-labs
                - /data/private.txt
            Principal: '*'

# allow with acl, deny with resource filter?
# add deny to public* principals on specific resource