Resources:
  s3ReaderPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: s3_reader_user_lab_1_2_2_jdix
      Path: '/'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:ListAllMyBuckets
          Resource: '*'
  s3User:
    Type: AWS::IAM::User
    Properties:
      Path: "/"
      UserName: '{{resolve:ssm:su-retro-1-2-jdix:1}}' 
      ManagedPolicyArns:
        - Ref: s3ReaderPolicy
Outputs:
  s3ReaderPolicy:
    Value: !Ref s3ReaderPolicy
    Description: "this is for a lab"
    Export:
      Name: "lab-2-1-2-s3ReaderPolicyArn-jdix"